version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestExtPAfterDisableProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TestExtPAfterDisableProject
  gitUsername: PoojaAnandGit
  gitBranch: main
